### ISSUE TITLE
Incompatible with denite.nvim namespace feature.

### ISSUE THREAD

**Issue by kiooss** [5t111111/denite-rails#4]
> denite-rails should move modules directory to the other place.

See https://github.com/Shougo/denite.nvim/issues/455

**Comment by 5t111111** [comment]
Sorry for the inconvenience. I will try to fix it this weekend.

**Comment by 5t111111** [comment]
@kiooss I've fixed this issue just by pulling the directory from the source directory for the moment.
Please update to the latest version and check if it works!

**Comment by kiooss** [comment]
Work like a charm again! Thanks.
